[cerebrium.deployment]
name = "lucid-society"
python_version = "3.12"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = false
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.hardware]
cpu = 3
memory = 16.0
compute = "AMPERE_A10"

[cerebrium.dependencies.pip]
diffusers = "latest"
accelerate = "latest"
torch = "latest"
transformers = "latest"
stable-audio-tools = "latest"
torchaudio = "latest"
googletrans = "3.1.0a0"
numba = "latest"
bitsandbytes = "latest"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 100
scaling_buffer = 0

